### ISSUE TITLE
`-p\d+` and `-patch\d+` releases aren't merged together correctly with existing stable releases

### ISSUE THREAD

**Issue by Ocramius** [Roave/SecurityAdvisoriesBuilder#91]
See https://github.com/Roave/SecurityAdvisories/commit/b04afa5560ac7f34fe6a24c620ccb199d61624a0
See https://github.com/FriendsOfPHP/security-advisories/commit/f502efb11448b466f8022cf8c6fb394e760ae163
See https://github.com/FriendsOfPHP/security-advisories/pull/424

**Comment by stof** [comment]
There is 2 issues here:

- the magento advisories are broken, by having 2 upper bounds in the range. This is fixed by https://github.com/FriendsOfPHP/security-advisories/pull/425, with https://github.com/FriendsOfPHP/security-advisories/pull/426 adding a check in the validator to prevent it from happening again
- the SecurityAdvisoriesBuilder has a wrong handling of `-p` release. It currently implement this as `2.3.2-p2 < 2.3.2-alpha1 < 2.3.2-beta1 < 2.3.2-rc1 < 2.3.2 < 2.3.3-alpha1`. But this is not how composer (and PHP's `version_compare`) treat them. The right behavior is `2.3.2-alpha1 < 2.3.2-beta1 < 2.3.2-rc1 < 2.3.2 < 2.3.2-p2 < 2.3.3-alpha1`. Note that `2.3.2-p` releases are higher than 2.3.2.

**Comment by slash3b** [comment]
Hopefully it is fixed in https://github.com/Roave/SecurityAdvisoriesBuilder/pull/98

**Comment by Ocramius** [comment]
Handled in #98 by @slash3b 💃
